# Generated by Django 6.1 on 2026-09-04 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='built_area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Metros cuadrados totales construidos de la obra.', max_digits=10, verbose_name='Superficie construida (m2)'),
        ),
        migrations.AddField(
            model_name='project',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('6.9700'), help_text='Tipo de cambio aplicable (Bs por USD).', max_digits=8, verbose_name='Tipo de cambio (USD)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('budget', 'En Presupuesto'), ('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('completed', 'Finalizada')], default='budget', max_length=20, verbose_name='Estado de la obra'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='core_proj_name_idx'),
        ),
    ]
