# Generated by Django 6.1 on 2026-09-08 15:12

import core.models.project_document
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_built_area_project_exchange_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(help_text='Ej: Cotización Fierro Corrugado 1/2 - Las Lomas', max_length=255, verbose_name='Título o Concepto')),
                ('document_type', models.CharField(choices=[('quotation', 'Cotización de Materiales'), ('invoice', 'Comprobante / Factura'), ('technical_sheet', 'Ficha Técnica'), ('blueprint', 'Plano / Especificación'), ('other', 'Otro Documento')], db_index=True, default='quotation', max_length=30, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to=core.models.project_document.project_document_upload_path, verbose_name='Archivo adjunto')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('file_extension', models.CharField(blank=True, default='', max_length=15, verbose_name='Extensión')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Proveedor / Empresa')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto cotizado')),
                ('currency', models.CharField(choices=[('BOB', 'Bolivianos (Bs)'), ('USD', 'Dólares ($)')], default='BOB', max_length=3, verbose_name='Moneda')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas u observaciones')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project', verbose_name='Obra / Proyecto')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.subcategory', verbose_name='Subcategoría vinculada')),
            ],
            options={
                'verbose_name': 'Documento de Obra',
                'verbose_name_plural': 'Documentos de Obra',
                'db_table': 'core_project_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'document_type'], name='core_pdoc_proj_type_idx'), models.Index(fields=['project', '-created_at'], name='core_pdoc_proj_date_idx')],
            },
        ),
    ]
