# Generated by Django 6.1 on 2026-09-08 15:48

import core.models.project_expense
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Cotización / Proforma'), ('technical_sheet', 'Ficha Técnica'), ('blueprint', 'Plano / Especificación'), ('other', 'Otro Respaldo')], db_index=True, default='quotation', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category_type', models.CharField(choices=[('materials', 'Materiales'), ('labor', 'Mano de Obra'), ('operating', 'Gastos Operativos'), ('administrative', 'Costos Administrativos'), ('other', 'Otros Gastos')], db_index=True, default='materials', max_length=30, verbose_name='Tipo de Categoría')),
                ('item_name', models.CharField(help_text='Ej: Barra de acero corrugado 3/8"x12m. (10mm²)', max_length=255, verbose_name='Descripción del Ítem')),
                ('unit_name', models.CharField(default='Pza', help_text='Ej: Barra, Rollo, m³, Kg, Gbl', max_length=50, verbose_name='Unidad')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Unitario (Bs)')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Precio Total (Bs)')),
                ('payment_status', models.CharField(choices=[('paid', 'Pagado'), ('in_process', 'En proceso'), ('pending', 'Por cobrar')], db_index=True, default='paid', max_length=20, verbose_name='Estado de Pago')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Fecha de Compra / Pago')),
                ('payment_method', models.CharField(blank=True, default='AL CONTADO', help_text='Ej: AL CONTADO, PAGADO CON FAR, TRANSFERENCIA BANCARIA', max_length=100, verbose_name='Forma de Pago / Modalidad')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Proveedor / Empresa / Contratista')),
                ('details', models.TextField(blank=True, default='', help_text='Ej: Se pagó con factura pero será devuelto el precio del mismo', verbose_name='Detalle / Observaciones')),
                ('rendicion_number', models.CharField(blank=True, db_index=True, default='', help_text='Ej: Nr° 04 o Rendición 01', max_length=50, verbose_name='N° de Rendición de Fondos')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=core.models.project_expense.project_expense_receipt_path, verbose_name='Factura / Comprobante adjunto')),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100, verbose_name='N° de Factura o Recibo')),
                ('receipt_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre original del comprobante')),
                ('receipt_file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.project', verbose_name='Obra / Proyecto')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Ej: Acero Corrugado, Hormigón Premezclado, Estructuras', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.subcategory', verbose_name='Subcategoría / Etapa')),
            ],
            options={
                'verbose_name': 'Gasto Real de Obra',
                'verbose_name_plural': 'Gastos Reales de Obra',
                'db_table': 'core_project_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['project', '-expense_date'], name='core_pexp_proj_date_idx'), models.Index(fields=['project', 'category_type'], name='core_pexp_proj_cat_idx'), models.Index(fields=['project', 'payment_status'], name='core_pexp_proj_stat_idx'), models.Index(fields=['project', 'rendicion_number'], name='core_pexp_proj_rend_idx')],
            },
        ),
    ]
