# Generated by Django 6.1 on 2026-08-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_purchaseunit_unitofmeasure_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='1 unidad_purchase = X unidad_measure. Ej: 1 barra = 12.00 ml. Nulo permitido solo para ítems globales (is_global=True) en presupuesto.', max_digits=10, null=True, verbose_name='Factor de conversión')),
                ('weight_per_purchase_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Peso en kg de 1 unidad_purchase. Solo informativo/reportería (ej. sumar toneladas de fierro), no afecta el cálculo de compra.', max_digits=10, null=True, verbose_name='Peso por unidad de compra')),
                ('waste_pct', models.DecimalField(decimal_places=4, default=0, help_text='Desperdicio estimado (ej. 0.10 = 10%). En catálogo es el valor sugerido; en presupuesto es el valor aplicable a la obra.', max_digits=5, verbose_name='Porcentaje de desperdicio')),
                ('price_per_purchase_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Costo o precio por unidad de compra (ej. Bs por barra/bolsa/balde). En catálogo es referencial; en presupuesto es el precio de la obra.', max_digits=15, null=True, verbose_name='Precio por unidad de compra')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_catalog_items', to='core.subcategory', verbose_name='Subcategoría')),
                ('unit_measure', models.ForeignKey(help_text='Unidad en la que se cuantifica la necesidad en obra (ej. ml, m2, m3, kg).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='Unidad de medida')),
                ('unit_purchase', models.ForeignKey(help_text='Unidad comercial en la que se adquiere (ej. barra, bolsa, tubo, balde, Gbl).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.purchaseunit', verbose_name='Unidad de compra')),
            ],
            options={
                'verbose_name': 'Ítem de Catálogo de Materiales',
                'verbose_name_plural': 'Ítems de Catálogo de Materiales',
                'ordering': ['subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, help_text='1 unidad_purchase = X unidad_measure. Ej: 1 barra = 12.00 ml. Nulo permitido solo para ítems globales (is_global=True) en presupuesto.', max_digits=10, null=True, verbose_name='Factor de conversión')),
                ('weight_per_purchase_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Peso en kg de 1 unidad_purchase. Solo informativo/reportería (ej. sumar toneladas de fierro), no afecta el cálculo de compra.', max_digits=10, null=True, verbose_name='Peso por unidad de compra')),
                ('waste_pct', models.DecimalField(decimal_places=4, default=0, help_text='Desperdicio estimado (ej. 0.10 = 10%). En catálogo es el valor sugerido; en presupuesto es el valor aplicable a la obra.', max_digits=5, verbose_name='Porcentaje de desperdicio')),
                ('price_per_purchase_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Costo o precio por unidad de compra (ej. Bs por barra/bolsa/balde). En catálogo es referencial; en presupuesto es el precio de la obra.', max_digits=15, null=True, verbose_name='Precio por unidad de compra')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('detail', models.CharField(blank=True, help_text='Marca, color, especificación puntual para esta obra.', max_length=255, verbose_name='Detalle / Especificación')),
                ('is_global', models.BooleanField(default=False, help_text='Marcar si es una compra en paquete/global sin cómputo métrico.', verbose_name='¿Es ítem global?')),
                ('quantity_obra', models.DecimalField(blank=True, decimal_places=4, help_text='Cómputo neto requerido en obra (solo para ítems no globales).', max_digits=15, null=True, verbose_name='Cantidad requerida en obra')),
                ('quantity_purchase', models.DecimalField(decimal_places=4, help_text='Cantidad a comprar en unidad comercial. Calculada o ingresada directamente.', max_digits=15, verbose_name='Cantidad a comprar')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_budget_items', to='core.project', verbose_name='Proyecto')),
                ('subcategory', models.ForeignKey(help_text='Subcategoría para organización y agrupación del presupuesto en obra.', on_delete=django.db.models.deletion.PROTECT, related_name='material_budget_items', to='core.subcategory', verbose_name='Subcategoría')),
                ('unit_measure', models.ForeignKey(help_text='Unidad en la que se cuantifica la necesidad en obra (ej. ml, m2, m3, kg).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='Unidad de medida')),
                ('unit_purchase', models.ForeignKey(help_text='Unidad comercial en la que se adquiere (ej. barra, bolsa, tubo, balde, Gbl).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.purchaseunit', verbose_name='Unidad de compra')),
                ('catalog_item', models.ForeignKey(blank=True, help_text='Referencia al ítem de catálogo de origen (solo trazabilidad, no se usa en cálculos).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_instances', to='materials.materialcatalogitem', verbose_name='Ítem de catálogo origen')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto de Materiales',
                'verbose_name_plural': 'Ítems de Presupuesto de Materiales',
                'ordering': ['project', 'subcategory', 'name'],
            },
        ),
    ]
