# Generated by Django 6.1 on 2026-08-20 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbudgetitem',
            options={'ordering': ['project', 'subcategory__name', 'name'], 'verbose_name': 'Ítem de Presupuesto de Materiales', 'verbose_name_plural': 'Ítems de Presupuesto de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='materialcatalogitem',
            options={'ordering': ['subcategory__name', 'name'], 'verbose_name': 'Ítem de Catálogo de Materiales', 'verbose_name_plural': 'Ítems de Catálogo de Materiales'},
        ),
        migrations.AddField(
            model_name='materialbudgetitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialbudgetitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='materialcatalogitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcatalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterModelTable(
            name='materialbudgetitem',
            table='materials_budget_item',
        ),
        migrations.AlterModelTable(
            name='materialcatalogitem',
            table='materials_catalog_item',
        ),
    ]
