# Generated by Django 6.1 on 2026-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subcategory_unique_together_and_more'),
        ('materials', '0002_alter_materialbudgetitem_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialbudgetitem',
            index=models.Index(fields=['project', 'subcategory'], name='mat_bud_proj_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='materialbudgetitem',
            index=models.Index(fields=['project', 'is_global'], name='mat_bud_proj_global_idx'),
        ),
        migrations.AddIndex(
            model_name='materialbudgetitem',
            index=models.Index(fields=['project', 'catalog_item'], name='mat_bud_proj_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcatalogitem',
            index=models.Index(fields=['subcategory', 'is_active'], name='mat_cat_subcat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcatalogitem',
            index=models.Index(fields=['is_active'], name='mat_cat_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcatalogitem',
            index=models.Index(fields=['name'], name='mat_cat_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialbudgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_purchase__gte', 0)), name='check_mat_bud_quantity_purchase_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='materialbudgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_obra__gte', 0), ('quantity_obra__isnull', True), _connector='OR'), name='check_mat_bud_quantity_obra_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='materialbudgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_purchase_unit__gte', 0), ('price_per_purchase_unit__isnull', True), _connector='OR'), name='check_mat_bud_price_non_negative'),
        ),
    ]
