# Generated by Django 6.1 on 2026-09-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_subcategory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Herramienta',
                'verbose_name_plural': 'Categorías de Herramientas',
                'db_table': 'inventory_tool_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la locación')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código de locación')),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Almacén / Depósito Central'), ('PROJECT', 'Frente de Obra'), ('WORKSHOP', 'Taller de Mantenimiento'), ('OTHER', 'Otro')], db_index=True, default='WAREHOUSE', max_length=20, verbose_name='Tipo de locación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección / Ubicación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_locations', to='core.project', verbose_name='Obra vinculada')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'db_table': 'inventory_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de activo / inventario')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle / Especificación')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible en Almacén'), ('IN_USE', 'En Uso / En Obra'), ('MAINTENANCE', 'En Mantenimiento / Reparación'), ('DAMAGED', 'Dañada / Fuera de Servicio'), ('LOST', 'Extraviada / De Baja')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Estado operativo')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de compra')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools_currently_here', to='inventory.location', verbose_name='Ubicación actual')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.toolcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Herramienta / Maquinaria',
                'verbose_name_plural': 'Herramientas y Maquinarias',
                'db_table': 'inventory_tool',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del traslado')),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable en terreno / Receptor')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones / Motivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tool_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por (Usuario del sistema)')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.location', verbose_name='Locación de destino')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.location', verbose_name='Locación de origen')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.tool', verbose_name='Herramienta / Equipo')),
            ],
            options={
                'verbose_name': 'Traslado de Herramienta',
                'verbose_name_plural': 'Traslados de Herramientas',
                'db_table': 'inventory_tool_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type', 'is_active'], name='inventory_l_locatio_f3dc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['project', 'is_active'], name='inventory_l_project_c45c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['current_location', 'status'], name='inventory_t_current_261e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'status'], name='inventory_t_categor_39d83b_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['code', 'is_active'], name='inventory_t_code_30d78a_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltransfer',
            index=models.Index(fields=['tool', '-transfer_date'], name='inventory_t_tool_id_51e263_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltransfer',
            index=models.Index(fields=['destination_location', '-transfer_date'], name='inventory_t_destina_660edf_idx'),
        ),
    ]
