# Generated by Django 6.1 on 2026-09-04 20:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_project_built_area_project_exchange_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la tarea')),
                ('detail', models.CharField(blank=True, help_text='Especificaciones de colocación, herramientas incluidas, alcance.', max_length=255, verbose_name='Detalle técnico / Especificación')),
                ('suggested_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarifa referencial de mercado en Bolivianos.', max_digits=15, verbose_name='Costo sugerido (Bs)')),
                ('contractor_type', models.CharField(blank=True, help_text='Ej: Albañilería, Plomería, Electricista, Marmolería.', max_length=150, verbose_name='Tipo de contratista sugerido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_catalog_items', to='core.subcategory', verbose_name='Subcategoría / Etapa')),
                ('unit', models.ForeignKey(help_text='Unidad en la que se cuantifica la labor (m2, ml, punto, pza, Gbl, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Ítem de Catálogo de Mano de Obra',
                'verbose_name_plural': 'Ítems de Catálogo de Mano de Obra',
                'db_table': 'labor_catalog_item',
                'ordering': ['subcategory__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LaborBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contractor_name', models.CharField(blank=True, help_text='Nombre del contratista o cuadrilla asignada (ej: Contratista Obra Gris).', max_length=150, verbose_name='Contratista / Especialidad')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la tarea')),
                ('detail', models.CharField(blank=True, help_text='Especificación puntual para esta obra (ej: arranca desde viga de fundación).', max_length=255, verbose_name='Detalle / Alcance específico')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Metrado neto ejecutado o contratado.', max_digits=15, verbose_name='Cantidad / Cómputo')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Tarifa pactada en Bolivianos por cada unidad.', max_digits=15, verbose_name='Costo Unitario (Bs)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_budget_items', to='core.project', verbose_name='Proyecto')),
                ('subcategory', models.ForeignKey(help_text='Etapa constructiva de la obra (Obra Gris, Fina, Eléctrica, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='labor_budget_items', to='core.subcategory', verbose_name='Subcategoría / Etapa')),
                ('unit', models.ForeignKey(help_text='Unidad en la que se cuantifica la labor (m2, ml, punto, pza, Gbl, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure', verbose_name='Unidad de medida')),
                ('catalog_item', models.ForeignKey(blank=True, help_text='Referencia histórica al catálogo maestro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_instances', to='labor.laborcatalogitem', verbose_name='Ítem de catálogo origen')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto de Mano de Obra',
                'verbose_name_plural': 'Ítems de Presupuesto de Mano de Obra',
                'db_table': 'labor_budget_item',
                'ordering': ['project', 'subcategory__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='laborcatalogitem',
            index=models.Index(fields=['subcategory', 'is_active'], name='labor_cat_subcat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='laborcatalogitem',
            index=models.Index(fields=['is_active'], name='labor_cat_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='laborcatalogitem',
            index=models.Index(fields=['name'], name='labor_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='laborbudgetitem',
            index=models.Index(fields=['project', 'subcategory'], name='labor_bud_proj_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='laborbudgetitem',
            index=models.Index(fields=['project', 'contractor_name'], name='labor_bud_proj_cont_idx'),
        ),
        migrations.AddIndex(
            model_name='laborbudgetitem',
            index=models.Index(fields=['project', 'catalog_item'], name='labor_bud_proj_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborbudgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='check_labor_bud_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='laborbudgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='check_labor_bud_cost_non_negative'),
        ),
    ]
